#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*" -> "}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${app_path##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H cannot be redirected.  We could set max in the
        # environment and then check the value of the environment variable.
        # However, that doesn't work if the parent shell doesn't pass the environment.
        # Thus, we set the soft limit from the hard limit.
        ulimit -n -H 2>/dev/null || { # Try to set both hard and soft.
            # If we can't set the hard limit, we set the soft limit to the maximum that we can.
            # The hard limit must be "max" or "unlimited" (maybe "unlimited" is not a valid argument).
            ulimit -n -H 2>/dev/null &&                 # if this works, try to set the soft limit.
                ulimit -n -S $( ulimit -n -H )          # and set the soft limit to the hard limit.
        } || {
            # Otherwise we set the soft limit to 4096.
            ulimit -n -S 4096
        }
    esac
fi

# Collect all arguments for the java command, stacking in reverse order to eventually pass to java.
# We stack in reverse order because the "exec" java command uses the 0th argument $0 (which is this script)
# and then everything else starting with $1, then $2, etc. appended to it.

# We start with the accumulated set of options (from $APP_CMDLINE_OPTIONS, $JAVA_OPTS, $GRADLE_OPTS, and $DEFAULT_JVM_OPTS)
# Then we add the module path and the classpath.
# Then we add the module patches (probably something like `--patch-module`).
# Then we add the rest of the arguments (originally set as $*).
# Then we add the log arguments (which are handled specially).
# Finally we add the execution directory (which is also handled specially).

# Prepend any user-defined options.
APP_CMDLINE_OPTIONS="$@"

# Create a variable that holds the final set of options for java.
final_opts=""

# Start with the defaults.
final_opts="$final_opts $DEFAULT_JVM_OPTS"

# Then add the module patches.
final_opts="$final_opts --patch-module=java.base=$APP_HOME/gradle/patches/java.base"

# Then add the module path.
final_opts="$final_opts --module-path=$APP_HOME/gradle/wrapper"

# Then add the classpath.
final_opts="$final_opts --class-path $CLASSPATH"

# Then add the module arguments.
final_opts="$final_opts org.gradle.wrapper.GradleWrapperMain"

# Then add the original arguments (from $APP_CMDLINE_OPTIONS).
final_opts="$final_opts $APP_CMDLINE_OPTIONS"

# Determine the Java command to use to start the JVM with the final options.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H cannot be redirected.  We could set max in the
        # environment and then check the value of the environment variable.
        # However, that doesn't work if the parent shell doesn't pass the environment.
        # Thus, we set the soft limit from the hard limit.
        ulimit -n -H 2>/dev/null || { # Try to set both hard and soft.
            # If we can't set the hard limit, we set the soft limit to the maximum that we can.
            # The hard limit must be "max" or "unlimited" (maybe "unlimited" is not a valid argument).
            ulimit -n -H 2>/dev/null &&                 # if this works, try to set the soft limit.
                ulimit -n -S $( ulimit -n -H )          # and set the soft limit to the hard limit.
        } || {
            # Otherwise we set the soft limit to 4096.
            ulimit -n -S 4096
        }
    esac
fi

# Collect all arguments for the java command, stacking in reverse order to eventually pass to java.
# We stack in reverse order because the "exec" java command uses the 0th argument $0 (which is this script)
# and then everything else starting with $1, then $2, etc. appended to it.

# We start with the accumulated set of options (from $APP_CMDLINE_OPTIONS, $JAVA_OPTS, $GRADLE_OPTS, and $DEFAULT_JVM_OPTS)
# Then we add the module path and the classpath.
# Then we add the module patches (probably something like `--patch-module`).
# Then we add the rest of the arguments (originally set as $*).
# Then we add the log arguments (which are handled specially).
# Finally we add the execution directory (which is also handled specially).

# Prepend any user-defined options.
APP_CMDLINE_OPTIONS="$@"

# Create a variable that holds the final set of options for java.
final_opts=""

# Start with the defaults.
final_opts="$final_opts $DEFAULT_JVM_OPTS"

# Then add the module patches.
final_opts="$final_opts --patch-module=java.base=$APP_HOME/gradle/patches/java.base"

# Then add the module path.
final_opts="$final_opts --module-path=$APP_HOME/gradle/wrapper"

# Then add the classpath.
final_opts="$final_opts --class-path $CLASSPATH"

# Then add the module arguments.
final_opts="$final_opts org.gradle.wrapper.GradleWrapperMain"

# Then add the original arguments (from $APP_CMDLINE_OPTIONS).
final_opts="$final_opts $APP_CMDLINE_OPTIONS"

# Execute Java
exec "$JAVACMD" $final_opts